<?php

/*
 * SMTP Konfigurator
 *
 * Package: vtinnovations/smtp-bundle
 * Copyright: VT Innovations Team
 * Licence: LGPL-3.0-or-later
 * Website: https://github.com/vtinnovations/smtp-bundle
 */

declare(strict_types=1);

namespace Vtinnovations\SmtpBundle\Tests\Fixture;

use Vtinnovations\SmtpBundle\Config\DeploymentProfile;
use Vtinnovations\SmtpBundle\Support\CanonicalForm;
use Vtinnovations\SmtpBundle\Support\TrustedKeys;

/**
 * Builds genuinely signed packages for the tests, using a throwaway key pair.
 *
 * Signing here rather than pasting fixtures matters: the tests then exercise the same
 * canonicalisation the production path uses, so a change that breaks byte compatibility fails
 * loudly instead of passing against a snapshot that was generated by the same broken code.
 */
final class RecordFactory
{
    public readonly string $secretKey;
    public readonly string $publicKeyB64;

    private readonly CanonicalForm $canonicalForm;

    public function __construct(public readonly string $keyId = 'test-key-2026')
    {
        $pair = sodium_crypto_sign_keypair();

        $this->secretKey     = sodium_crypto_sign_secretkey($pair);
        $this->publicKeyB64  = base64_encode(sodium_crypto_sign_publickey($pair));
        $this->canonicalForm = new CanonicalForm();
    }

    public function keys(): TrustedKeys
    {
        return new TrustedKeys($this->publicKeyB64, '', $this->keyId, '');
    }

    /**
     * @param array<string, mixed> $overrides
     *
     * @return array<string, mixed>
     */
    public function document(array $overrides = []): array
    {
        $document = array_merge([
            'schema_version'      => DeploymentProfile::SCHEMA_VERSION,
            'project'             => DeploymentProfile::PROJECT,
            'project_slug'        => DeploymentProfile::PROJECT_SLUG,
            'license_key'         => 'AAAAA-BBBBB-CCCCC-DDDDD',
            'license_domain'      => 'example.com',
            'license_domains'     => ['example.com', 'staging.example.com'],
            'license_max_domains' => 3,
            'license_package'     => 'free',
            'license_features'    => [],
            'license_version'     => 7,
            'license_issued_at'   => 1784000000,
            'license_starts_at'   => 1784000000,
            'license_expires_at'  => null,
            'license_lifetime'    => true,
            'license_verified_at' => time(),
            'free_available'      => false,
            'validation_status'   => 'valid',
        ], $overrides);

        // Unsetting is how a test drops a field entirely rather than nulling it.
        return array_filter($document, static fn ($v): bool => '__unset__' !== $v);
    }

    /**
     * @param array<string, mixed> $document
     *
     * @return array<string, mixed>
     */
    public function signed(array $document): array
    {
        $document['signature'] = base64_encode(
            sodium_crypto_sign_detached($this->canonicalForm->of($document), $this->secretKey),
        );

        return $document;
    }

    /** @param array<string, mixed> $overrides */
    public function bytes(array $overrides = []): string
    {
        return (string) json_encode($this->signed($this->document($overrides)), JSON_UNESCAPED_SLASHES);
    }

    /**
     * @param array<string, mixed> $overrides
     *
     * @return array<string, mixed>
     */
    public function envelope(string $bytes, array $overrides = []): array
    {
        $document = json_decode($bytes, true);

        $envelope = array_merge([
            'project'             => DeploymentProfile::PROJECT,
            'project_slug'        => DeploymentProfile::PROJECT_SLUG,
            'license_version'     => \is_array($document) ? (int) ($document['license_version'] ?? 0) : 0,
            'license_md5'         => md5($bytes),
            'generated_at'        => time(),
            'key_id'              => $this->keyId,
            'signature_algorithm' => 'ed25519',
        ], $overrides);

        $envelope['signature'] = base64_encode(
            sodium_crypto_sign_detached($this->canonicalForm->of($envelope), $this->secretKey),
        );

        return $envelope;
    }

    /**
     * The five headers an inbound push carries, signed over the fixed six-line message.
     *
     * @param array<string, string> $overrides
     *
     * @return array{request_id: string, timestamp: string, nonce: string, key_id: string, signature: string}
     */
    public function requestHeaders(string $method, string $path, string $body, array $overrides = []): array
    {
        $headers = array_merge([
            'request_id' => 'req-'.bin2hex(random_bytes(6)),
            'timestamp'  => (string) time(),
            'nonce'      => 'nonce-'.bin2hex(random_bytes(6)),
            'key_id'     => $this->keyId,
        ], $overrides);

        $message = implode("\n", [
            strtoupper($method),
            $path,
            $headers['request_id'],
            $headers['timestamp'],
            $headers['nonce'],
            hash('sha256', $body),
        ]);

        $headers['signature'] = $overrides['signature']
            ?? base64_encode(sodium_crypto_sign_detached($message, $this->secretKey));

        return $headers;
    }

    /**
     * A complete delivery, as it arrives on the wire.
     *
     * @param array<string, mixed> $documentOverrides
     * @param array<string, mixed> $envelopeOverrides
     *
     * @return array{bytes: string, payload_b64: string, envelope: array<string, mixed>}
     */
    public function package(array $documentOverrides = [], array $envelopeOverrides = []): array
    {
        $bytes = $this->bytes($documentOverrides);

        return [
            'bytes'       => $bytes,
            'payload_b64' => base64_encode($bytes),
            'envelope'    => $this->envelope($bytes, $envelopeOverrides),
        ];
    }
}
